//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.24 at 04:39:06 PM IST 
//


package org.interland.ipsh.designationlist;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.interland.ipsh.designationlist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.interland.ipsh.designationlist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DepartmentRequest }
     * 
     */
    public DepartmentRequest createDepartmentRequest() {
        return new DepartmentRequest();
    }

    /**
     * Create an instance of {@link DepartmentSaveResponse }
     * 
     */
    public DepartmentSaveResponse createDepartmentSaveResponse() {
        return new DepartmentSaveResponse();
    }

    /**
     * Create an instance of {@link Designation }
     * 
     */
    public Designation createDesignation() {
        return new Designation();
    }

    /**
     * Create an instance of {@link DesignationList }
     * 
     */
    public DesignationList createDesignationList() {
        return new DesignationList();
    }

    /**
     * Create an instance of {@link DepartmentSaveRequest }
     * 
     */
    public DepartmentSaveRequest createDepartmentSaveRequest() {
        return new DepartmentSaveRequest();
    }

    /**
     * Create an instance of {@link DepartmentValidation }
     * 
     */
    public DepartmentValidation createDepartmentValidation() {
        return new DepartmentValidation();
    }

    /**
     * Create an instance of {@link DepartmentList }
     * 
     */
    public DepartmentList createDepartmentList() {
        return new DepartmentList();
    }

    /**
     * Create an instance of {@link TransactionsRequest }
     * 
     */
    public TransactionsRequest createTransactionsRequest() {
        return new TransactionsRequest();
    }

    /**
     * Create an instance of {@link TransactionDto }
     * 
     */
    public TransactionDto createTransactionDto() {
        return new TransactionDto();
    }

    /**
     * Create an instance of {@link TransactionResponse }
     * 
     */
    public TransactionResponse createTransactionResponse() {
        return new TransactionResponse();
    }

    /**
     * Create an instance of {@link GetDepartmentsRequest }
     * 
     */
    public GetDepartmentsRequest createGetDepartmentsRequest() {
        return new GetDepartmentsRequest();
    }

    /**
     * Create an instance of {@link SearchParamRequest }
     * 
     */
    public SearchParamRequest createSearchParamRequest() {
        return new SearchParamRequest();
    }

    /**
     * Create an instance of {@link SearchParam }
     * 
     */
    public SearchParam createSearchParam() {
        return new SearchParam();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

}
