//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.24 at 04:39:06 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/designationList", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.interland.ipsh.designationlist;
