//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.24 at 04:39:06 PM IST 
//


package org.interland.ipsh.designationlist;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="searchStatus" type="{http://www.example.org/designationList}status" maxOccurs="unbounded"/&gt;
 *         &lt;element name="searchData" type="{http://www.example.org/designationList}designation" maxOccurs="unbounded"/&gt;
 *         &lt;element name="totalDisplayRecord" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalRecords" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchStatus",
    "searchData",
    "totalDisplayRecord",
    "totalRecords"
})
@XmlRootElement(name = "searchResponse")
public class SearchResponse {

    @XmlElement(required = true)
    protected List<Status> searchStatus;
    @XmlElement(required = true)
    protected List<Designation> searchData;
    protected long totalDisplayRecord;
    protected long totalRecords;

    /**
     * Gets the value of the searchStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the searchStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Status }
     * 
     * 
     */
    public List<Status> getSearchStatus() {
        if (searchStatus == null) {
            searchStatus = new ArrayList<Status>();
        }
        return this.searchStatus;
    }

    /**
     * Gets the value of the searchData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the searchData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Designation }
     * 
     * 
     */
    public List<Designation> getSearchData() {
        if (searchData == null) {
            searchData = new ArrayList<Designation>();
        }
        return this.searchData;
    }

    /**
     * Gets the value of the totalDisplayRecord property.
     * 
     */
    public long getTotalDisplayRecord() {
        return totalDisplayRecord;
    }

    /**
     * Sets the value of the totalDisplayRecord property.
     * 
     */
    public void setTotalDisplayRecord(long value) {
        this.totalDisplayRecord = value;
    }

    /**
     * Gets the value of the totalRecords property.
     * 
     */
    public long getTotalRecords() {
        return totalRecords;
    }

    /**
     * Sets the value of the totalRecords property.
     * 
     */
    public void setTotalRecords(long value) {
        this.totalRecords = value;
    }

}
