//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.24 at 04:39:06 PM IST 
//


package org.interland.ipsh.designationlist;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="searchParam" type="{http://www.example.org/designationList}searchParam"/&gt;
 *         &lt;element name="iDisplayStart" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="iDisplayLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchParam",
    "iDisplayStart",
    "iDisplayLength"
})
@XmlRootElement(name = "searchParamRequest")
public class SearchParamRequest {

    @XmlElement(required = true)
    protected SearchParam searchParam;
    protected int iDisplayStart;
    protected int iDisplayLength;

    /**
     * Gets the value of the searchParam property.
     * 
     * @return
     *     possible object is
     *     {@link SearchParam }
     *     
     */
    public SearchParam getSearchParam() {
        return searchParam;
    }

    /**
     * Sets the value of the searchParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchParam }
     *     
     */
    public void setSearchParam(SearchParam value) {
        this.searchParam = value;
    }

    /**
     * Gets the value of the iDisplayStart property.
     * 
     */
    public int getIDisplayStart() {
        return iDisplayStart;
    }

    /**
     * Sets the value of the iDisplayStart property.
     * 
     */
    public void setIDisplayStart(int value) {
        this.iDisplayStart = value;
    }

    /**
     * Gets the value of the iDisplayLength property.
     * 
     */
    public int getIDisplayLength() {
        return iDisplayLength;
    }

    /**
     * Sets the value of the iDisplayLength property.
     * 
     */
    public void setIDisplayLength(int value) {
        this.iDisplayLength = value;
    }

}
